version: "3"

services:
  piped:
    image: 1337kavin/piped:latest
    container_name: piped
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: piped-postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres:
