version: '3.5'
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - ${PORT}:8080
      - ${PORT_S}:8443
    environment:
      PUBLIC_DNS: ${PUBLIC_DNS}
      ORGANISATION_UNIT: unit
      ORGANISATION: org
      CITY: city
      STATE: state
      COUNTRY_CODE: country
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://$$PUBLIC_DNS || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s