version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=${DB_HOST}
      - SYMFONY__ENV__DATABASE_PORT=${DB_PORT}
      - SYMFONY__ENV__DATABASE_NAME=${DB_NAME}
      - SYMFONY__ENV__DATABASE_USER=${DB_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${DB_PASS}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__SECRET=${SECRET}
      - SYMFONY__ENV__LOCALE=${LOCALE}
      - SYMFONY__ENV__DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - ${PORT}:80
    volumes:
      - wallabag_data:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - wallabag_db
      - redis

  wallabag_db:
    image: mariadb:latest
    container_name: wallabag-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - wallabag_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30

    redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/var/lib/redis
      - send_redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  wallabag_db_data:
  wallabag_data: