version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=${DB_HOST}
      - SYMFONY__ENV__DATABASE_PORT=${DB_PORT}
      - SYMFONY__ENV__DATABASE_NAME=${DB_NAME}
      - SYMFONY__ENV__DATABASE_USER=${DB_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${DB_PASS}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__SECRET=${SECRET}
      - SYMFONY__ENV__LOCALE=${LOCALE}
      - SYMFONY__ENV__DOMAIN_NAME=${DOMAIN_NAME}
      - SYMFONY__ENV__REDIS_HOST=wallabag-redis
      - SYMFONY__ENV__REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${PORT}:80
    volumes:
      - wallabag_data:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: wallabag-db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - wallabag_db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: wallabag-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  wallabag_db_data:
  wallabag_data: