# Use postgres/example user/password credentials
version: "3.4"

volumes:
  database-data:

services:
  database:
    container_name: calcom-db
    image: postgres
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    container_name: calcom
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database

# Optional use of Prisma Studio. In production, comment out or remove the section below to prevent unwanted access to your database.
  studio:
    image: calcom.docker.scarf.sh/calcom/cal.com
    container_name: calcom-studio
    restart: unless-stopped
    ports:
      - 5555:5555
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
    command:
      - npx
      - prisma
      - studio
# END SECTION: Optional use of Prisma Studio.
