version: "3.3"

services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    container_name: calcom
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - TZ=${TZ}
    ports:
      - ${PORT}:3000
    depends_on:
      - database
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    # volumes:
      # - volume:/opt/example/data

  database:
    image: postgres
    container_name: calcom-db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    # ports:
    #   - ${PORT}:3000
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    volumes:
      - database-data:/var/lib/postgresql/data/

# networks:
#   proxy:
#     external: true

volumes:
  database-data: