version: "3"

services:
  version: '3.3'

services:
  matrix:
    image: matrixdotorg/synapse
    restart: unless-stopped
    environment:
       TZ: ${TZ}
       SYNAPSE_SERVER_NAME: ${SYNAPSE_SERVER_NAME}
       SYNAPSE_ENABLE_REGISTRATION: ${SYNAPSE_ENABLE_REGISTRATION}
       SYNAPSE_REPORT_STATS: ${SYNAPSE_REPORT_STATS}
    ports:
      - ${SYNAPSE_PORT}:8008
    volumes:
      - synapse_data:/data
    container_name: synapse

volumes:
  synapse_data: