services:

    app:
        build:
            context: .
            dockerfile: docker/php.dockerfile
        image: jez500/pricebuddy:latest
        ports:
            - 8080:80
        volumes:
            - storage:/app/storage
            - ./.env:/app/.env
        environment:
            DB_HOST: database                       # Name of the database service
            DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
            DB_PASSWORD: pric3buddy                 # Should match the MYSQL_PASSWORD in the database service
            DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
            APP_USER_EMAIL: admin@example.com       # Only used for seeding the database
            APP_USER_PASSWORD: admin                # Only used for seeding the database
            SCRAPER_BASE_URL: http://scraper:3000   # Url to Name of the scrapper service
            AFFILIATE_ENABLED: 'true'               # See https://pricebuddy.jez.me/support-project.html
        depends_on:
            - database
        networks:
            - default

    database:
        image: mysql:8.2
        environment:
            MYSQL_DATABASE: pricebuddy
            MYSQL_USER: pricebuddy
            MYSQL_PASSWORD: pric3buddy
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - database:/var/lib/mysql
        networks:
            - default

    scraper:
        image: amerkurev/scrapper:latest
        networks:
            - default
        ports:
            - 3030:3000 # Optional, if you want to access the scrapper api from the host machine

volumes:
    storage:
    database:

networks:
    default:
