- id: '1705880903000'
  alias: 'Bedroom No Motion Detected '
  description: 'Turn off lights when no motion detected in bedroom '
  trigger:
  - type: not_occupied
    platform: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: 84bb9612e7943123511181346286d369
      entity_id: 5a22f32ddf813584bf8116a23e686b02
      domain: light
    - condition: device
      type: is_on
      device_id: c3024e452e7dc1ef53408a3e22d22ac4
      entity_id: b6c683846c299b1235f3992974740673
      domain: light
    - condition: device
      type: is_on
      device_id: d829a9f141cf19469f5437f7a519e1ec
      entity_id: e3e0498ae514a1d15a53c8c47270fbf9
      domain: light
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1705883368133'
  alias: Bedroom Motion Detected After 5:30 PM
  description: Turn on work light when motion detected in bedroom
  trigger:
  - type: occupied
    platform: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  condition:
  - condition: time
    after: '17:30:00'
    before: '20:30:00'
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
  - condition: device
    type: is_off
    device_id: d829a9f141cf19469f5437f7a519e1ec
    entity_id: e3e0498ae514a1d15a53c8c47270fbf9
    domain: light
  action:
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.bedroom_hue_work
  mode: single
- id: '1705886186671'
  alias: Bedroom Motion Detected After 9:30 PM
  description: Turn on play light when motion detected in bedroom
  trigger:
  - type: occupied
    platform: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  condition:
  - condition: time
    after: '21:30:00'
    before: '21:58:00'
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
  - condition: device
    type: is_off
    device_id: c3024e452e7dc1ef53408a3e22d22ac4
    entity_id: b6c683846c299b1235f3992974740673
    domain: light
  action:
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 255
      - 147
      - 0
      brightness_pct: 70
    target:
      entity_id: light.window_light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.bed_light
      - light.work_light
  mode: single
- id: '1705886408814'
  alias: Bedroom Motion Detected After 8:30 PM
  description: Turn on bed light when motion detected in bedroom
  trigger:
  - type: occupied
    platform: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  condition:
  - condition: time
    after: '20:30:00'
    before: '21:30:00'
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
  - condition: device
    type: is_off
    device_id: 84bb9612e7943123511181346286d369
    entity_id: 5a22f32ddf813584bf8116a23e686b02
    domain: light
  action:
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 247
      - 206
      - 70
      brightness_pct: 100
    target:
      entity_id: light.bed_light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.window_light
      - light.work_light
  mode: single
- id: '1705936894417'
  alias: Bedroom Wake Up
  description: Wake up at 6
  trigger:
  - platform: time
    at: 06:00:00
  condition:
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  action:
  - service: light.turn_on
    metadata: {}
    data:
      transition: 5
      rgb_color:
      - 247
      - 206
      - 70
      brightness_pct: 100
    target:
      entity_id: light.bed_light
  mode: single
- id: '1705937169769'
  alias: Bedroom Go To Sleep
  description: Go to sleep at 10
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  action:
  - service: light.turn_off
    metadata: {}
    data:
      transition: 5
    target:
      area_id: bedroom
  mode: single
- id: '1705962943616'
  alias: 'Bedroom Fan Off On Weekend '
  description: Turn off fan
  trigger:
  - platform: time
    at: 06:00:00
  condition:
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  - condition: time
    weekday:
    - sat
    - sun
  - condition: device
    type: is_on
    device_id: ae0e1ba093830f63d0539dc482714a3f
    entity_id: b49b237ccab62259ca1463dc59171ce6
    domain: switch
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_fan_outlet_switch
  mode: single
- id: '1705967414316'
  alias: Bedroom Purifier Off
  description: Turn off air purifier when quality is good
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.jya_fjord_airpurifier_pro_pm2_5
    below: 12
  condition:
  - condition: device
    device_id: 8d896de00eb78f121b706f07d78c846b
    domain: fan
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    type: is_on
  action:
  - type: turn_off
    device_id: 8d896de00eb78f121b706f07d78c846b
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    domain: fan
  mode: single
- id: '1705967499479'
  alias: Bedroom Purifier On
  description: Turn on air purifier when quality is bad
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.jya_fjord_airpurifier_pro_pm2_5
    above: 20
  condition:
  - condition: device
    device_id: 8d896de00eb78f121b706f07d78c846b
    domain: fan
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    type: is_off
  action:
  - type: turn_on
    device_id: 8d896de00eb78f121b706f07d78c846b
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    domain: fan
  mode: single
- id: '1706022564476'
  alias: 'Bridge Motion Detected '
  description: 'Turn on bridge light when motion detected '
  trigger:
  - type: motion
    platform: device
    device_id: b4a58bd4bdb311c9fd5f2b30d84aa7c3
    entity_id: fc9ae81990f11ed191ba88d16c3c23b5
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 5e324cfbb68205d646bd01c136d0b111
    entity_id: 17b7363111529b01fec5eff1c2e3c31f
    domain: binary_sensor
  condition:
  - condition: time
    after: '17:45:00'
    before: 06:30:00
  - condition: device
    type: is_off
    device_id: b06c134fa6942a16fa8deaafdac97c17
    entity_id: a6a2dc8aeae74234c975235fd0376a46
    domain: switch
  action:
  - type: turn_on
    device_id: b06c134fa6942a16fa8deaafdac97c17
    entity_id: a6a2dc8aeae74234c975235fd0376a46
    domain: switch
  mode: single
- id: '1706109072417'
  alias: 'Bridge No Motion Detected '
  description: 'Turn off bridge light when motion not detected '
  trigger:
  - type: no_motion
    platform: device
    device_id: b4a58bd4bdb311c9fd5f2b30d84aa7c3
    entity_id: fc9ae81990f11ed191ba88d16c3c23b5
    domain: binary_sensor
  - type: no_motion
    platform: device
    device_id: 5e324cfbb68205d646bd01c136d0b111
    entity_id: 17b7363111529b01fec5eff1c2e3c31f
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: b06c134fa6942a16fa8deaafdac97c17
    entity_id: a6a2dc8aeae74234c975235fd0376a46
    domain: switch
  action:
  - type: turn_off
    device_id: b06c134fa6942a16fa8deaafdac97c17
    entity_id: a6a2dc8aeae74234c975235fd0376a46
    domain: switch
  mode: single
- id: '1706111216140'
  alias: Bedroom Fan Off On Weekdays
  description: Turn off fan
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: device
    type: is_on
    device_id: ae0e1ba093830f63d0539dc482714a3f
    entity_id: b49b237ccab62259ca1463dc59171ce6
    domain: switch
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_fan_outlet_switch
  mode: single
- id: '1706111283093'
  alias: Bedroom Fan Off At Night
  description: Turn off fan
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  - condition: device
    type: is_on
    device_id: ae0e1ba093830f63d0539dc482714a3f
    entity_id: b49b237ccab62259ca1463dc59171ce6
    domain: switch
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.bedroom_fan_outlet_switch
  mode: single
- id: '1706137374612'
  alias: Bedroom Fan On
  description: Turn on fan in the morning
  trigger:
  - platform: time
    at: 04:30:00
  condition:
  - condition: device
    type: is_off
    device_id: ae0e1ba093830f63d0539dc482714a3f
    entity_id: b49b237ccab62259ca1463dc59171ce6
    domain: switch
  - type: is_motion
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 88a889df056de98610dcf5df46a2c240
    domain: binary_sensor
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  action:
  - type: turn_on
    device_id: ae0e1ba093830f63d0539dc482714a3f
    entity_id: b49b237ccab62259ca1463dc59171ce6
    domain: switch
  mode: single
- id: '1706187413295'
  alias: Bathroom 1 Motion Detected 5:30 PM
  description: Turn on light when motion is detected in bathroom
  trigger:
  - type: occupied
    platform: device
    device_id: c2e301741319635965dc1ed5a8a06b7a
    entity_id: bd4ced3baf851822b0d330af9a2c398d
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 365e992081bdc2a2e207829a2a4166be
    entity_id: f12a7fe74b833630b0a3519884be5261
    domain: light
  - condition: time
    after: '17:30:00'
    before: '21:00:00'
  action:
  - service: light.turn_on
    metadata: {}
    data:
      transition: 5
      rgb_color:
      - 255
      - 147
      - 0
      brightness_pct: 100
    target:
      device_id: 365e992081bdc2a2e207829a2a4166be
  mode: single
- id: '1706187513421'
  alias: Bathroom 1 No Motion Detected
  description: Turn on light when motion is detected in bathroom
  trigger:
  - type: not_occupied
    platform: device
    device_id: c2e301741319635965dc1ed5a8a06b7a
    entity_id: bd4ced3baf851822b0d330af9a2c398d
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 365e992081bdc2a2e207829a2a4166be
    entity_id: f12a7fe74b833630b0a3519884be5261
    domain: light
  action:
  - type: turn_off
    device_id: 365e992081bdc2a2e207829a2a4166be
    entity_id: f12a7fe74b833630b0a3519884be5261
    domain: light
  mode: single
- id: '1706187983283'
  alias: Bathroom 1 Motion Detected 9PM
  description: Turn on light when motion is detected in bathroom
  trigger:
  - type: occupied
    platform: device
    device_id: c2e301741319635965dc1ed5a8a06b7a
    entity_id: bd4ced3baf851822b0d330af9a2c398d
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 365e992081bdc2a2e207829a2a4166be
    entity_id: f12a7fe74b833630b0a3519884be5261
    domain: light
  - condition: time
    after: '21:00:00'
    before: 06:30:00
  action:
  - service: light.turn_on
    metadata: {}
    data:
      transition: 5
      rgb_color:
      - 255
      - 147
      - 0
      brightness_pct: 50
    target:
      device_id: 365e992081bdc2a2e207829a2a4166be
  mode: single
- id: '1706190166910'
  alias: Notify when windows are opened at night
  description: ''
  trigger:
  - platform: time
    at: '21:30:00'
  condition:
  - condition: or
    conditions:
    - type: is_open
      condition: device
      device_id: 1e14c085f63f9a593cf59bed32976e04
      entity_id: 5edd50df24f2a25c8ae1813f9c9d7032
      domain: binary_sensor
    - type: is_open
      condition: device
      device_id: 3ae7a5e53b23beeb0ea7d6b636dd3cdf
      entity_id: bbea47c58e691b96706541d431f0392f
      domain: binary_sensor
    - type: is_open
      condition: device
      device_id: 66a02e82868cf86f26706e73037c4815
      entity_id: 9d426040679461c76608e60f051e3e38
      domain: binary_sensor
    - type: is_open
      condition: device
      device_id: 26aaf5b98ad95b08c439b5e35e25559d
      entity_id: 3b54f7f885dd0e5470e052b6aaf9c658
      domain: binary_sensor
    - type: is_open
      condition: device
      device_id: b2eb097a2a147546c098cc0c3e2949eb
      entity_id: 748532f847c0135db86554619c7f749a
      domain: binary_sensor
  action:
  - service: notify.notify
    metadata: {}
    data:
      message:    ^p      ng c         a anh Q       i
  mode: single
- id: '1706397308514'
  alias: Bedroom Motion Detected 8:30PM
  description: Turn on bed light when motion detected in bedroom
  trigger:
  - platform: time
    at: '20:30:00'
  condition:
  - condition: device
    type: is_off
    device_id: 84bb9612e7943123511181346286d369
    entity_id: 5a22f32ddf813584bf8116a23e686b02
    domain: light
  - condition: device
    type: is_on
    device_id: d829a9f141cf19469f5437f7a519e1ec
    entity_id: e3e0498ae514a1d15a53c8c47270fbf9
    domain: light
  - type: is_occupied
    condition: device
    device_id: 1b0bd18f6332b721725804484fa65d85
    entity_id: 5800c25901beeb825895e47402f7131b
    domain: binary_sensor
  action:
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 247
      - 206
      - 70
      brightness_pct: 100
    target:
      entity_id: light.bed_light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.window_light
      - light.work_light
  mode: single
- id: '1706409852291'
  alias: Bedroom Purifier On At 11AM
  description: Turn on air purifier at 11AM
  trigger:
  - platform: time
    at: '11:00:00'
  condition:
  - condition: device
    device_id: 8d896de00eb78f121b706f07d78c846b
    domain: fan
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    type: is_off
  action:
  - type: turn_on
    device_id: 8d896de00eb78f121b706f07d78c846b
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    domain: fan
  mode: single
- id: '1706409925495'
  alias: Bedroom Purifier On At 4PM
  description: Turn on air purifier at 4PM
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: device
    device_id: 8d896de00eb78f121b706f07d78c846b
    domain: fan
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    type: is_off
  action:
  - type: turn_on
    device_id: 8d896de00eb78f121b706f07d78c846b
    entity_id: 1d46579426d506bf62d27ef0e596cd64
    domain: fan
  mode: single
