version: "3"

services:
  libreddit:
    image: spikecodes/libreddit:arm
    ports:
      - "${LIBREDDIT_PORT}:8080"
    restart: unless-stopped
    container_name: libreddit
    environment:
      - LIBREDDIT_DEFAULT_POST_SORT="new"