version: "3.7"

services:

  server:
    image: avhost/docker-matrix:v1.60.0@sha256:954bcced5b79c1b9188260519f50b1eeebbc97d903ec1cc402e3c721deea335d
    user: "1000:1000"
    restart: unless-stopped
    container_name: synapse
    stop_grace_period: 1m
    entrypoint: "bash"
    command: "-c './start.py generate && ./start.py migrate_config && exec ./start.py'"
    volumes:
      - synapse_data:/data
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_HTTP_PORT: "${SYNAPSE_HTTP_PORT}"
      SYNAPSE_SERVER_NAME: "${SYNAPSE_SERVER_NAME}"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_ENABLE_REGISTRATION: "yes"
      SYNAPSE_NO_TLS: "yes"

volumes:
  synapse_data: