services:
  db:
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - vikunja_db_data:/var/lib/mysql
    restart: unless-stopped
    container_name: vikunja-db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s

  vikunja:
    image: vikunja/vikunja
    ports:
      - ${PORT}:3456
    environment:
      # VIKUNJA_API_URL: ${VIKUNJA_API_URL}
      VIKUNJA_SERVICE_PUBLICURL: ${SERVICE_PUBLICURL}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${MYSQL_USER}
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${SERVICE_JWTSECRET}
    restart: unless-stopped
    container_name: vikunja
    volumes:
      - vikunja_data:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy

volumes:
  vikunja_db_data:
  vikunja_data: