version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "caddy", "version"]
    networks:
      - caddy
    labels:
      caddy.email: ${CADDY_EMAIL}
    container_name: caddy

volumes:
  caddy_data:
    external: true
  caddy_config: