version: "3.3"

services:
  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - ${PORT}:80
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

  db:
    image: mariadb
    container_name: baikal-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: baikal
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db:/var/lib/mysql

volumes:
  config:
  data:
  db:

# networks:
#   proxy:
#     external: true