version: "3.8"

services:
  ergo:
    image: ghcr.io/ergochat/ergo:stable
    ports:
      - "${PORT}:6667/tcp"
      - "${PORT_TLS}:6697/tcp"
    volumes:
      - data:/ircd
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
      replicas: 1

volumes:
  data: