version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        ports:
            - ${SPEEDTEST_PORT}:80
            - ${SPEEDTEST_PORT_443}:443
        volumes:
            - speedtest_data:/config
            - speedtest_data_web:/etc/ssl/web'
        environment:
            - TZ=${TZ}
            - PGID=1000
            - PUID=1000
        restart: unless-stopped

volumes:
  speedtest_data:
  speedtest_data_web: