version: "2.1"
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - budge_data:/config
    ports:
      - ${PORT}:80
      - ${PORT_HTTPS}:443
    restart: unless-stopped

volumes:
  budge_data: