---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Utilities:
    # - ChangeDetection:
    #     - icon: changedetection-io.png
    #       href: http://192.168.1.5:19960
    - RSS:
        - icon: miniflux.png
          href: http://192.168.1.4:19994
    - Read:
        - icon: wallabag.png
          href: http://192.168.1.4:19976
    - Link:
        - icon: linkding.png
          href: http://192.168.1.4:19989
    # - Memos:
    #     - icon: memos.png
    #       href: http://192.168.1.4:19969
    - Money:
        - icon: actual.png
          href: http://192.168.1.4:19970
    # - Grocy:
    #     - icon: grocy.png
    #       href: http://192.168.1.4:19961
    # - Monica:
    #     - icon: monica.png
    #       href: http://192.168.1.4:19991
    - Reddit:
        - icon: libreddit.png
          href: http://192.168.1.4:19986
    - SpeedTest:
        - icon: speedtest-tracker.png
          href: http://192.168.2.5:19993/
    - Pomofocus:
        - abbr: UT
          href: https://pomofocus.io/

- Youtube:
    - Muse VN:
        - icon: youtube-kids.png
          href: https://www.youtube.com/c/MuseVi%E1%BB%87tNam/videos
    - Bilibili:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@MadeByBilibili-Vietnam/videos
    - Amigoscode:
        - icon: youtube-kids.png
          href: https://www.youtube.com/c/amigoscode/videos
    - Java for Beginners:
        - icon: youtube-kids.png
          href: https://www.youtube.com/playlist?list=PLlrxD0HtieHgX3ExVDMlKjdN8LJsks2CM
    - Rachel's English:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@rachelsenglish/videos
    - BBC Learning English:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@bbclearningenglish/videos
    - VOA Learning English:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@voalearningenglish/videos
    - TED-Ed:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@TEDEd/videos
    - TED:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@TED/videos
    - TheEllenShow:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@TheEllenShow/videos
    - Hana's Lexis:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@hanaslexis/videos
    - British Council LearnEnglish:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@BritishCouncilEnglish/videos
    - EnglishClass101:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@EnglishClass101/videos