---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Raspberry:
    - Selfhosted:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/selfhosted/new
    - WebApps:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/WebApps/new

- Apps:
    - AppHookup:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/AppHookup/new
    - MacApps:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/MacApps/new
    - iOSApps:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/iOSApps/new
    - AppleWatchApps:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/AppleWatchApps/new
    - Airpods:
        - icon: reddit.png
          href: http://192.168.1.4:19986/r/Airpods/new

- Relax:
    - Muse VN:
        - icon: youtube-kids.png
          href: https://www.youtube.com/c/MuseVi%E1%BB%87tNam/videos

- Utilities:
    - Pomofocus:
        - abbr: UT
          href: https://pomofocus.io/

- Study:
    - Web5Ngay:
        - icon: youtube-kids.png
          href: https://www.youtube.com/c/Web5Ngay/videos
    - Amigoscode:
        - icon: youtube-kids.png
          href: https://www.youtube.com/c/amigoscode/videos
    - Java for Beginners:
        - icon: youtube-kids.png
          href: https://www.youtube.com/playlist?list=PLlrxD0HtieHgX3ExVDMlKjdN8LJsks2CM
    - Rachel's English:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@rachelsenglish/videos
    - BBC Learning English:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@bbclearningenglish/videos
    - VOA Learning English:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@voalearningenglish/videos
    - TED-Ed:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@TEDEd/videos
    - TED:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@TED/videos
    - TheEllenShow:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@TheEllenShow/videos
    - Hana's Lexis:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@hanaslexis/videos
    - British Council LearnEnglish:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@BritishCouncilEnglish/videos
    - EnglishClass101:
        - icon: youtube-kids.png
          href: https://www.youtube.com/@EnglishClass101/videos