version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0 # The PUID can be set to 0 which will give root permissions to the container
      - PGID=0  # The PGID can be set to 0 which will give root permissions to the container
      - TZ=${TZ} # Set the appropriate timezone
      - CLI_ARGS=--no-local-blocks=false
    volumes:
      - /docker/duplicati_data:/data:rw # Contains all relevant configuration files. Volume Mount to the config folder of all your docker containers
      - /docker/backups:/backups:rw # Path to store local backups. If the backup needs to be stored on your machine, add a volume mount to that path here
      - /var/lib/docker/volumes:/docker_volumes:ro # docker volume ls => docker inspect volume name => volume location
      - </home/user-name/raspberry>:/docker_source:ro # cd raspberry => pwd => raspberry source location
    ports:
      - ${DUPLICATI_PORT}:8200
    restart: unless-stopped