version: "3"

services:
  actual:
    image: jlongster/actual-server
    container_name: actual-server
    restart: unless-stopped
    ports:
      - ${PORT}:5006
    volumes:
      - actual_data:/data

volumes:
  actual_data: