blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/data/hostsVN/hosts
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - |
        # inline definition with YAML literal block scalar style
        someadsdomain.com
        *.dable.io
  clientGroupsBlock:
    default:
      - ads

# customDNS:
#   customTTL: 1h
#   filterUnmappedTypes: true
#   mapping:
#     home.example.com: 192.168.1.4:19992
#     link.example.com: 192.168.1.4:19989
#     memos.example.com: 192.168.1.4:19969
#     money.example.com: 192.168.1.4:19970
#     rd.example.com: 192.168.1.4:19986
#     read.example.com: 192.168.1.4:19975
#     rss.example.com: 192.168.1.4:19994
    # rewrite:
    #   example.com: printer.lan

ports:
  dns: 53
  http: 4000

upstreams:
  groups:
    default:
      - 1.1.1.1 # Cloudflare
      - 1.0.0.1 # Cloudflare
      - 8.8.8.8 # Google
      - 8.8.4.4 # Google
      - 208.67.222.222
      - 208.67.220.220
      - tcp-tls:fdns1.dismail.de:853
      - https://dns.digitale-gesellschaft.ch/dns-query