version: "3"

services:
  gotify:
    image: gotify/server:2.1.14
    ports:
      - ${GOTIFY_SERVER_PORT}:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
      - TZ=${TZ}
    volumes:
      - "gotify_data:/app/data"


volumes:
  gotify_data: