version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:dev-arm
        ports:
            - ${SPEEDTEST_PORT}:80
        volumes:
            - speedtest_data:/config
        environment:
            - TZ=${TZ}
            - PGID=
            - PUID=
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
        env_file:
            ../config/speedtest.env

volumes:
  speedtest_data: