version: "3.8"

services:
  srv:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - ${PORT}:80/tcp
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    environment:
      - TZ=${TZ}
      - FTLCONF_REPLY_ADDR4=${FTLCONF_REPLY_ADDR4}
      - WEBPASSWORD=${WEBPASSWORD}
      - WEBTHEME=${WEBTHEME}
      - DNSMASQ_LISTENING=${DNSMASQ_LISTENING}
    volumes:
      - config:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - log:/var/log
    healthcheck:
      test: dig @127.0.0.1 pi.hole || exit 1
      interval: 2m00s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  config:
  dnsmasq:
  log: