version: "3.8"

services:
  srv:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      # DNS Ports
      - 53:53/tcp
      - 53:53/udp
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Default HTTP Port
      - ${PORT}:80/tcp
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
    # cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      # - SYS_NICE
    environment:
      - TZ=${TZ}
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      - FTLCONF_webserver_interface_theme=${WEBTHEME}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      - FTLCONF_dns_listeningMode=${DNS_LISTENINGMODE}
      - FTLCONF_dns_upstreams=${DNS_UPSTREAMS}
    volumes:
      - config:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      # - dnsmasq:/etc/dnsmasq.d
      - log:/var/log
    healthcheck:
      test: dig @127.0.0.1 pi.hole || exit 1
      interval: 2m00s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  config:
  # dnsmasq:
  log: