version: '3'
services:
  shiori:
    image: malitov/rpi-shiori
    container_name: shiori
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "${PORT}:8080"
    volumes:
      - shiori_data:/srv/shiori

volumes:
  shiori_data: