version: '3.6'

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:3000
    restart: unless-stopped