version: '2.4'

services:

  frontend:
    image: "grocy/frontend:v3.3.2"
    container_name: grocy
    depends_on:
      - backend
    ports:
      - '${PORT}:8080'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v3.3.2"
    container_name: grocy-db
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - app-db:/var/www/data
    restart: unless-stopped

volumes:
  app-db:
