services:
  tududi:
    image: chrisvel/tududi:latest
    container_name: tududi
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:3002
    volumes:
      - data:/app/backend/db

volumes:
  data:

