services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT:-3000}:3000
    healthcheck:
      test: curl --fail http://localhost:${PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro