version: '3'
services:
  wallabag:
    image: abhilesh7/wallabag-arm
    container_name: wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=${MYSQL_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=smtp.gmail.com                             # Using gmail's smtp server
      - SYMFONY__ENV__MAILER_USER=<smtp-user>                                # Change this
      - SYMFONY__ENV__MAILER_PASSWORD=<smtp-user-password>                   # Change this
      - SYMFONY__ENV__FROM_EMAIL=<smtp-user-email>                           # Change this
      - SYMFONY__ENV__DOMAIN_NAME=${DOMAIN_NAME}
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    # If using watchtower, uncomment the line below to disable automatic updates
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - ${PORT}:80                                                              # Serving on port '8543', can change to a different port
    volumes:
      - wallabag_data:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis

  db:
    image: mariadb
    container_name: wallabag-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - wallabag_db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: wallabag-redis

volumes:
  wallabag_db_data:
  wallabag_data: