version: "3.7"

services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - TAKE_FILE_OWNERSHIP=false
    ports:
      - ${PORT}:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    volumes:
      - data:/data
      - ./config:/config:ro

volumes:
  data: