version: "2.1"

services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - grav_data:/config
    ports:
      - ${PORT}:80
    restart: unless-stopped

volumes:
  grav_data: