version: "3"

services:
  homeserver:
    image: matrixconduit/matrix-conduit:latest
    container_name: conduit
    restart: unless-stopped
    ports:
      - ${PORT}:6167
    volumes:
      - db:/var/lib/matrix-conduit/
    environment:
      CONDUIT_SERVER_NAME: ${CONDUIT_SERVER_NAME}
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: "true"
      CONDUIT_ALLOW_FEDERATION: "true"
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
      #CONDUIT_LOG: info,rocket=off,_=off,sled=off
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_CONFIG: "" # Ignore this

volumes:
  db:
