version: '3'

services:
  linkding:
    image: sissbruecker/linkding:latest
    ports:
      - "${PORT}:9090"
    volumes:
      - linkding_data:/etc/linkding/data
    restart: unless-stopped
    container_name: linkding

volumes:
  linkding_data: