version: '3'

services:
  linkding:
    image: sissbruecker/linkding:latest
    ports:
      - "${PORT}:9090"
    volumes:
      - linkding_data:/etc/linkding/data
    restart: unless-stopped
    container_name: linkding

  backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    volumes:
      - backup_volume:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BACKUP_DIR}/linkding:/archive

volumes:
  linkding_data:
  backup_volume: