version: "3.3"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=${TZ}
    # ports:
    #   - ${PORT}:8123
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    network_mode: host
    volumes:
      # - db_volume:/opt/example/data
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

# networks:
#   proxy:
#     external: true

# volumes:
#   db_volume: