version: '3'

services:
  postgres:
    image: postgres
    container_name: reactive-resume-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: reactive-resume-server
    environment:
      - TZ=UTC
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - SENDGRID_API_KEY=
      - SENDGRID_FORGOT_PASSWORD_TEMPLATE_ID=
      - SENDGRID_FROM_NAME=
      - SENDGRID_FROM_EMAIL=
      - STORAGE_BUCKET=
      - STORAGE_REGION=
      - STORAGE_ENDPOINT=
      - STORAGE_URL_PREFIX=
      - STORAGE_ACCESS_KEY=
      - STORAGE_SECRET_KEY=
    depends_on:
      - postgres
    restart: unless-stopped

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactive-resume-client
    environment:
      - TZ=${TZ}
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - PUBLIC_GOOGLE_CLIENT_ID=
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false
    depends_on:
      - server
    restart: unless-stopped

volumes:
  pgdata:
