version: "3.3"

services:
  sun-panel:
    image: hslr/sun-panel
    container_name: sun-panel
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - ${PORT}:3002
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    volumes:
      - ./conf:/app/conf
      - db:/app/database
      - uploads:/app/uploads

volumes:
  db:
  uploads:

# networks:
#   proxy:
#     external: true