services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: vikunja-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s

  vikunja:
    image: vikunja/vikunja
    ports:
      - ${PORT}:3456
    env_file: .env
    restart: unless-stopped
    container_name: vikunja
    volumes:
      - data:/app/vikunja/files
      - ./config.yml:/etc/vikunja/config.yml
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  data: