version: '3'

services:
  db:
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - vikunja_db_data:/var/lib/mysql
    restart: unless-stopped
    container_name: vikunja-db

  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${MYSQL_USER}
      VIKUNJA_DATABASE_DATABASE: vikunja
    ports:
      - ${API_PORT}:3456
    volumes:
      - vikunja_data:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
    container_name: vikunja-api

  frontend:
    image: vikunja/frontend
    ports:
      - ${PORT}:80
    environment:
      VIKUNJA_API_URL: ${VIKUNJA_API_URL}
    restart: unless-stopped
    container_name: vikunja

volumes:
  vikunja_db_data:
  vikunja_data: