version: "3"

services:
  wordpress_db:
    image: mariadb:latest
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: wordpress-db

  wordpress_app:
    depends_on:
      - wordpress_db
    image: arm64v8/wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    container_name: wordpress
    env_file:
      ../config/wordpress.env

volumes:
  wp_db_data:
  wp_data:

