services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    env_file: .env
    # environment:
    #   - TZ=${TZ}
    ports:
      - ${PORT}:8090
    healthcheck:
      # The URL is relative to the container, not the host
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s # Check 5 seconds after the container starts
      interval: 120s # Then check every 120 seconds after that
    # networks:
    #   - proxy
    volumes:
      - data:/beszel_data

volumes:
  data:

# networks:
#   proxy:
#     external: true