version: "3.4"
services:
  db:
    image: postgres:latest
    container_name: joplin-server-db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Not working due to v15
  # https://github.com/tiredofit/docker-db-backup/issues/181
  # db-backup:
  #   container_name: joplin-server-db-backup
  #   image: ghcr.io/tiredofit/docker-db-backup
  #   links:
  #    - db
  #   volumes:
  #     - /home/ezcafe/backups/joplin-server:/backup
  #     - /home/ezcafe/raspberry/scripts/backup-post-script.sh:/assets/custom-scripts/post-script.sh
  #   environment:
  #     # - DEBUG_MODE=TRUE
  #     - DB01_TYPE=pgsql
  #     - DB01_HOST=${DB_HOST}
  #     - DB01_NAME=${DB_NAME}
  #     - DB01_USER=${DB_USER}
  #     - DB01_PASS=${DB_PASS}
  #     # - DB_PORT=${DB_PORT}    # TODO test this
  #     # - DEFAULT_BACKUP_BEGIN=0000    # backup starts immediately
  #     - DEFAULT_BACKUP_INTERVAL=1440       # backup every x minute - 1440 = 1 day
  #     - DEFAULT_CLEANUP_TIME=11520   # clean backups they are older than x minute - 11520 = 8 days
  #     - DEFAULT_CHECKSUM=SHA1
  #     - DEFAULT_COMPRESSION=GZ
  #     - DB01_SPLIT_DB=FALSE
  #     - CONTAINER_ENABLE_MONITORING=FALSE
  #     - TIMEZONE=${TZ}
  #   restart: unless-stopped

  app:
    image: joplin/server:latest
    container_name: joplin-server
    restart: unless-stopped
    ports:
      - ${PORT}:22300
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=${PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=${DB_PORT}
      - TZ=${TZ}
    #  TODO
    # healthcheck:
    #  test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]

volumes:
  db_volume:
