version: "3.3"

services:
  example:
    image: user/image:tag
    container_name: example
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - ${PORT}:8080
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    # volumes:
      # - example-data:/opt/example/data

# volumes:
#   example-data:

# networks:
#   proxy:
#     external: true