version: "2.1"
services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati
    environment:
      - TZ=${TZ} # Set the appropriate timezone
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /var/lib/docker/volumes:/docker_volumes:rw # docker volume ls => docker inspect volume name => volume location
      - duplicati_data:/config #Duplicati Config Files, for consisency across re-deployments
      - /home/ezcafe/backups:/backup_backups
      - /home/ezcafe/raspberry:/backup_raspberry
    ports:
      - ${DUPLICATI_PORT}:8200
    # healthcheck is not supported
    restart: unless-stopped

volumes:
  duplicati_data: