version: "3"
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - ZONE=${ZONE}
      - PROXIED=true
      - CRON="@daily"

  cloudflare-ddns-www:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - ZONE=${ZONE}
      - SUBDOMAIN=www
      - PROXIED=true
      - CRON="@daily"
