version: "3"
services:

  outline:
    image: outlinewiki/outline
    container_name: outline
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    container_name: outline-redis
    restart: unless-stopped
    ports:
      - "${PORT_REDIS}:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    container_name: outline-postgres
    restart: unless-stopped
    ports:
      - "${PORT_DB}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline

  storage:
    image: minio/minio
    container_name: outline-minio
    restart: unless-stopped
    ports:
      - "${PORT_MINIO}:9000"
    entrypoint: sh
    command: -c 'minio server'
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  storage-data:
  database-data:
