version: "3.7"
services:
  traggo:
    image: traggo/server:latest
    container_name: traggo
    restart: unless-stopped
    ports:
      - ${PORT}:3030
    environment:
      - TZ=${TZ}
    volumes:
      - traggo_data:/opt/traggo/data

  db-backup:
    container_name: traggo-db-backup
    image: ghcr.io/tiredofit/docker-db-backup
    links:
      - traggo
    volumes:
      - /home/ezcafe/backups/traggo:/backup
      - /home/ezcafe/raspberry/scripts/backup-post-script.sh:/assets/custom-scripts/post-script.sh
      - traggo_data:/opt/traggo/data
    environment:
      # - DEBUG_MODE=TRUE
      - DB01_TYPE=sqlite3
      - DB01_HOST=/opt/traggo/data/traggo.db
      # - DB01_NAME=${DB_NAME}
      # - DB01_USER=${DB_USER}
      # - DB01_PASS=${DB_PASS}
      # - DEFAULT_BACKUP_BEGIN=0000    # backup starts immediately
      - DEFAULT_BACKUP_INTERVAL=1440       # backup every x minute - 1440 = 1 day
      - DEFAULT_CLEANUP_TIME=11520   # clean backups they are older than x minute - 11520 = 8 days
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DB01_SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TIMEZONE=${TZ}
    restart: unless-stopped

volumes:
  traggo_data: