version: "3.3"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000
    network_mode: 'host'
    environment:
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${URL}
    # ports:
    #   - ${PORT}:8080
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      # - ./config:/config
      - cache:/cache
      - /home/ezcafe/backups/jellyfin:/media
      # - media2:/media2:ro

volumes:
  cache:
  media:

# networks:
#   proxy:
#     external: true