version: "3"
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}