services:
  cloudflare-ddns:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
