version: '3'
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DOZZLE_USERNAME=${DOZZLE_USERNAME}
      - DOZZLE_PASSWORD=${DOZZLE_PASSWORD}
      - DOZZLE_NO_ANALYTICS=${NO_ANALYTICS:-true}
      - DOZZLE_FILTER=${FILTER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:8080
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      # start_period: 30s