version: "3"

services:
  libreddit:
    image: quay.io/redlib/redlib:latest
    ports:
      - "${LIBREDDIT_PORT}:8080"
    restart: unless-stopped
    container_name: libreddit
    environment:
      - REDLIB_DEFAULT_COMMENT_SORT=top
      - REDLIB_DEFAULT_POST_SORT=new
      - REDLIB_DEFAULT_SHOW_NSFW=on
      - REDLIB_DEFAULT_THEME=dracula
      - REDLIB_DEFAULT_USE_HLS=on
      - REDLIB_DEFAULT_WIDE=on
