version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - freshrss_data:/config
    ports:
      - ${PORT}:80
    restart: unless-stopped

volumes:
  freshrss_data: