version: '3.7'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: ${TZ}
      PUID: 1000
      PGID: 1000
      CRON_MIN: '3,33'
    ports:
      - "${PUBLISHED_PORT:-8080}:${LISTEN:-80}"

volumes:
  freshrss_data:
  freshrss_extensions: