version: "3.7"
services:
  traggo:
    image: traggo/server:latest
    container_name: traggo
    restart: unless-stopped
    ports:
      - ${PORT}:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: ${USER}
      TRAGGO_DEFAULT_USER_PASS: ${PASS}
      TZ: ${TZ}
    volumes:
      - traggo_data:/opt/traggo/data

  db-backup:
    container_name: traggo-db-backup
    image: tiredofit/db-backup
    links:
      - traggo
    volumes:
      - /home/ezcafe/backups/traggo:/backup
      - /home/ezcafe/raspberry/scripts/backup-post-script.sh:/assets/custom-scripts/post-script.sh
      - traggo_data:/opt/traggo/data
    environment:
      # - DEBUG_MODE=TRUE
      - DB_TYPE=sqlite3
      - DB_HOST=/opt/traggo/data/traggo.db
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
      # - DB_PASS=${DB_PASS}
      # - DB_DUMP_BEGIN=0000    # backup starts immediately
      - DB_DUMP_FREQ=1440       # backup every x minute - 1440 = 1 day
      - DB_CLEANUP_TIME=11520   # clean backups they are older than x minute - 11520 = 8 days
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=${TZ}
    restart: unless-stopped

volumes:
  traggo_data: