version: "3"
services:

  wiki_db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    container_name: wikijs-db

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wiki_db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki_db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "${WIKI_PORT}:3000"
    container_name: wikijs

volumes:
  data: