version: "3"
services:

  wiki_db:
    container_name: wikijs-db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data

  wiki:
    container_name: wikijs
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wiki_db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki_db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    volumes:
      - ~/.ssh/wikijs_id_rsa:/etc/wiki/keys/id_rsa

  db-backup:
    container_name: wikijs-db-backup
    image: tiredofit/db-backup
    links:
     - wiki_db
    volumes:
      - /home/ezcafe/backups/wikijs:/backup
      - /home/ezcafe/raspberry/scripts/backup-post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      # - DEBUG_MODE=TRUE
      - DB_TYPE=pgsql
      - DB_HOST=wiki_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      # - DB_DUMP_BEGIN=0000      # backup starts immediately
      - DB_DUMP_FREQ=1440       # backup every x minute - 1440 = 1 day
      - DB_CLEANUP_TIME=11520   # clean backups they are older than x minute - 11520 = 8 days
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
      - TZ=${TZ}
    restart: unless-stopped

volumes:
  data: