# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":${MINIO_PORT_2}" http://minio{1...2}/data{1...2}
  expose:
    - "${MINIO_PORT_1}"
    - "${MINIO_PORT_2}"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT_1}/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - minio1-data-1:/data1
      - minio1-data-2:/data2
    container_name: minio1
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - minio2-data-1:/data1
      - minio2-data-2:/data2
    container_name: minio2

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio1-data-1:
  minio1-data-2:
  minio2-data-1:
  minio2-data-2:
