services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:8080
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # networks:
    #   - proxy
    volumes:
      - ./config/glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

# volumes:
#   data:

# networks:
#   proxy:
#     external: true