version: '3.7'

services:
  redis:
    container_name: searxng-redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    tmpfs:
      - /var/lib/redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
     - "${PORT}:8080"
    volumes:
      - searxng_data:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost/healthz"]
      interval: 1m
      timeout: 3s

volumes:
  searxng_data: