version: '3.7'

services:
  redis:
    container_name: searxng-redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    tmpfs:
      - /var/lib/redis
    restart: unless-stopped

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
     - "${PORT}:8080"
    volumes:
      - searxng_data:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
    restart: unless-stopped

volumes:
  searxng_data: