version: '3.7'

services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    restart: unless-stopped
    ports:
      - 3333:3333
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}

  postgres:
    image: postgres:12
    container_name: ghostfolio-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    container_name: ghostfolio-redis
    restart: unless-stopped

volumes:
  postgres: