version: '3.7'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
    ports:
      - 3333:3333

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'

volumes:
  postgres: