version: "3"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: nginx-proxy-manager-db

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '${PORT}:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      INITIAL_ADMIN_EMAIL: ${ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # Postgres parameters:
      DB_POSTGRES_HOST: 'db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_NAME: ${DB_NAME}
      DB_POSTGRES_USER: ${DB_USER}
      DB_POSTGRES_PASSWORD: ${DB_PASS}
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    container_name: nginx-proxy-manager

volumes:
  db_data:
  data:
  letsencrypt:
