version: "3"
services:

  wiki_db:
    container_name: wikijs-db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data

  wiki:
    container_name: wikijs
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wiki_db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki_db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    volumes:
      - ~/.ssh/wikijs_id_rsa:/etc/wiki/keys/id_rsa

  # db-backup:
  #   container_name: wikijs-db-backup
  #   image: ghcr.io/tiredofit/docker-db-backup
  #   links:
  #    - wiki_db
  #   volumes:
  #     - /home/ezcafe/backups/wikijs:/backup
  #     - /home/ezcafe/raspberry/scripts/backup-post-script.sh:/assets/custom-scripts/post-script.sh
  #   environment:
  #     # - DEBUG_MODE=TRUE
  #     - DB01_TYPE=pgsql
  #     - DB01_HOST=wiki_db
  #     - DB01_NAME=${DB_NAME}
  #     - DEFAULT_AUTH=${DB_NAME}
  #     - DB01_USER=${DB_USER}
  #     - DB01_PASS=${DB_PASS}
  #     # - DEFAULT_BACKUP_BEGIN=0000      # backup starts immediately
  #     - DEFAULT_BACKUP_INTERVAL=1440       # backup every x minute - 1440 = 1 day
  #     - DEFAULT_CLEANUP_TIME=11520   # clean backups they are older than x minute - 11520 = 8 days
  #     - DEFAULT_CHECKSUM=SHA1
  #     - DEFAULT_COMPRESSION=GZ
  #     - DB01_SPLIT_DB=FALSE
  #     - CONTAINER_ENABLE_MONITORING=FALSE
  #     - TIMEZONE=${TZ}
  #   restart: unless-stopped

volumes:
  data: