version: "3.4"

services:
  monica_app:
    image: monica
    depends_on:
      - monica_db
    ports:
      - ${MONICA_PORT}:80
    volumes:
      - monica_data:/var/www/html/storage
    restart: unless-stopped
    container_name: monica

  monica_db:
    image: jsurf/rpi-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - monica_db_data:/var/lib/mysql
    restart: unless-stopped
    container_name: monica-db

volumes:
  monica_data:
  monica_db_data: