version: "3.4"

services:
  monica_app:
    image: monica
    depends_on:
      - monica_db
    ports:
      - ${MONICA_PORT}:80
    volumes:
      - monica_data:/var/www/html/storage
    restart: unless-stopped
    environment:
      APP_KEY: ${APP_KEY}
      DB_HOST: monica_db:3306
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    container_name: monica

  monica_db:
    image: mariadb:latest
    volumes:
      - monica_db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    container_name: monica-db

volumes:
  monica_data:
  monica_db_data: