version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    # save 1 or more writes every 20 seconds to disk in case the server restarts
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  cache: