version: '3'

services:
  crater:
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    container_name: crater
    networks:
      - crater

  crater_db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - crater_db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '33006:3306'
    container_name: crater-db
    networks:
      - crater

  crater_nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 19987:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - crater

  cron:
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    container_name: crater-cron
    networks:
      - crater

volumes:
  crater_db_data:

networks:
  crater:
    driver: bridge