upstream:
  default:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 208.67.222.222
    - 208.67.220.220
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  rewrite:
    home.in4.vn: 192.168.1.4:19992
    link.in4.vn: 192.168.1.4:19989
    memos.in4.vn: 192.168.1.4:19969
    money.in4.vn: 192.168.1.4:19970
    rd.in4.vn: 192.168.1.4:19986
    read.in4.vn: 192.168.1.4:19975
    rss.in4.vn: 192.168.1.4:19994
  mapping:
    in4.lan: 192.168.1.4
    357.lan: 192.168.1.5