version: "3.8"

services:
  srv:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PORT}:4000/tcp
    environment:
      - TZ=${TZ}
    volumes:
      - ./config.yml:/app/config.yml
    healthcheck:
      test: dig @127.0.0.1 pi.hole || exit 1
      interval: 2m00s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  config:
  dnsmasq:
  log: